name: Build and push Docker image (Azure Container Registry)

on:
  push:
    branches:
      - main

jobs:
    acr-upload:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          env:
             SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
             USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
             PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          with:
            login-server: env.SERVER
            username: env.USERNAME
            password: env.PASSWORD
        - run: |
            docker build --file docker/Dockerfile -t env.SERVER/bacquerya_api:latest .
            docker push env.SERVER/bacquerya_api:latest