name: Build and push Docker image (Azure Container Registry)

on:
  push:
    branches:
      - main

jobs:
    acr-upload:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
            password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/bacquerya_api:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/bacquerya_api:latest