name: Build and push Docker image (Azure Container Registry)

on:
  push:
    branches:
      - main

jobs:
    acr-upload:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Step 2 - GitHub Action if statement (true)
          env: 
             WHO_TO_TRUST: ${{ secrets.TEST_SECRET }}
          if:  env.WHO_TO_TRUST == 'TrustNo1'
          run: echo "I know what the secret token is!"
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
            password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        - run: |
            docker build --file docker/Dockerfile -t bacquerya.azurecr.io/bacquerya_api:latest .
            docker push bacquerya.azurecr.io/bacquerya_api:latest
