name: Build and push Docker image (dockerhub)

on:
  push:
    branches:
      - main

jobs:
  docker-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Build and push
      id: bacquerya-api
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY_USERNAME }}/bacquerya-api:latest
        file: docker/Dockerfile
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
